# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(191, 41)
        self.pushButton_splittool = QtWidgets.QPushButton(Dialog)
        self.pushButton_splittool.setGeometry(QtCore.QRect(40, 10, 24, 24))
        self.pushButton_splittool.setObjectName("pushButton_splittool")
        self.pushButton_kundendaten = QtWidgets.QPushButton(Dialog)
        self.pushButton_kundendaten.setGeometry(QtCore.QRect(130, 10, 24, 24))
        self.pushButton_kundendaten.setObjectName("pushButton_kundendaten")
        self.pushButton_kabel_verlegen = QtWidgets.QPushButton(Dialog)
        self.pushButton_kabel_verlegen.setGeometry(QtCore.QRect(10, 10, 24, 24))
        self.pushButton_kabel_verlegen.setObjectName("pushButton_kabel_verlegen")
        self.pushButton_trasse_verwalten = QtWidgets.QPushButton(Dialog)
        self.pushButton_trasse_verwalten.setGeometry(QtCore.QRect(70, 10, 24, 24))
        self.pushButton_trasse_verwalten.setObjectName("pushButton_trasse_verwalten")
        self.pushButton_leerrohr_verwalten = QtWidgets.QPushButton(Dialog)
        self.pushButton_leerrohr_verwalten.setGeometry(QtCore.QRect(100, 10, 24, 24))
        self.pushButton_leerrohr_verwalten.setObjectName("pushButton_leerrohr_verwalten")
        self.pushButton_tool = QtWidgets.QPushButton(Dialog)
        self.pushButton_tool.setGeometry(QtCore.QRect(160, 10, 24, 24))
        self.pushButton_tool.setObjectName("pushButton_tool")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Toolbox"))
        self.pushButton_splittool.setText(_translate("Dialog", "Split Tool"))
        self.pushButton_kundendaten.setText(_translate("Dialog", "Kundendaten"))
        self.pushButton_kabel_verlegen.setText(_translate("Dialog", "Kabel Verlegen"))
        self.pushButton_trasse_verwalten.setText(_translate("Dialog", "Trasse Verwalten"))
        self.pushButton_leerrohr_verwalten.setText(_translate("Dialog", "Leerrohr Verwalten"))
        self.pushButton_tool.setText(_translate("Dialog", "Tool"))
