# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools\leerrohr_verbinder\leerrohr_verbinder_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KabelVerlegungsToolDialogBase(object):
    def setupUi(self, KabelVerlegungsToolDialogBase):
        KabelVerlegungsToolDialogBase.setObjectName("KabelVerlegungsToolDialogBase")
        KabelVerlegungsToolDialogBase.resize(593, 878)
        self.tabWidget = QtWidgets.QTabWidget(KabelVerlegungsToolDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 611, 831))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(0, 293, 591, 451))
        self.toolBox.setStyleSheet("QToolBox::tab { background-color: lightgreen; }\n"
"QToolBox::tab:selected { background-color: darkgrey; }")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 591, 395))
        self.page.setObjectName("page")
        self.graphicsView_Auswahl_Rrohr1 = QtWidgets.QGraphicsView(self.page)
        self.graphicsView_Auswahl_Rrohr1.setGeometry(QtCore.QRect(0, 0, 591, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_Auswahl_Rrohr1.sizePolicy().hasHeightForWidth())
        self.graphicsView_Auswahl_Rrohr1.setSizePolicy(sizePolicy)
        self.graphicsView_Auswahl_Rrohr1.setObjectName("graphicsView_Auswahl_Rrohr1")
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 591, 395))
        self.page_3.setObjectName("page_3")
        self.listWidget_Verbindungen = QtWidgets.QListWidget(self.page_3)
        self.listWidget_Verbindungen.setGeometry(QtCore.QRect(0, 0, 591, 391))
        self.listWidget_Verbindungen.setObjectName("listWidget_Verbindungen")
        self.toolBox.addItem(self.page_3, "")
        self.label_Status = QtWidgets.QLabel(self.tab)
        self.label_Status.setGeometry(QtCore.QRect(0, 752, 591, 53))
        self.label_Status.setStyleSheet("padding-left: 10px; padding-top: 5px;")
        self.label_Status.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Status.setText("")
        self.label_Status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Status.setWordWrap(True)
        self.label_Status.setObjectName("label_Status")
        self.pushButton_verbindung = QtWidgets.QPushButton(self.tab)
        self.pushButton_verbindung.setGeometry(QtCore.QRect(0, 3, 191, 25))
        self.pushButton_verbindung.setObjectName("pushButton_verbindung")
        self.label_gewaehltes_leerrohr1 = QtWidgets.QLabel(self.tab)
        self.label_gewaehltes_leerrohr1.setGeometry(QtCore.QRect(0, 233, 231, 22))
        self.label_gewaehltes_leerrohr1.setAutoFillBackground(False)
        self.label_gewaehltes_leerrohr1.setStyleSheet("background-color: lightcoral;")
        self.label_gewaehltes_leerrohr1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_gewaehltes_leerrohr1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_gewaehltes_leerrohr1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_gewaehltes_leerrohr1.setLineWidth(1)
        self.label_gewaehltes_leerrohr1.setObjectName("label_gewaehltes_leerrohr1")
        self.pushButton_verbindung_loeschen = QtWidgets.QPushButton(self.tab)
        self.pushButton_verbindung_loeschen.setGeometry(QtCore.QRect(150, 263, 141, 22))
        self.pushButton_verbindung_loeschen.setObjectName("pushButton_verbindung_loeschen")
        self.pushButton_leerrohr1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_leerrohr1.setGeometry(QtCore.QRect(0, 178, 191, 25))
        self.pushButton_leerrohr1.setObjectName("pushButton_leerrohr1")
        self.listWidget_Leerohr1 = QtWidgets.QListWidget(self.tab)
        self.listWidget_Leerohr1.setGeometry(QtCore.QRect(0, 102, 251, 71))
        self.listWidget_Leerohr1.setObjectName("listWidget_Leerohr1")
        self.pushButton_leerrohr2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_leerrohr2.setGeometry(QtCore.QRect(400, 178, 191, 25))
        self.pushButton_leerrohr2.setObjectName("pushButton_leerrohr2")
        self.listWidget_Leerohr2 = QtWidgets.QListWidget(self.tab)
        self.listWidget_Leerohr2.setGeometry(QtCore.QRect(350, 102, 241, 71))
        self.listWidget_Leerohr2.setObjectName("listWidget_Leerohr2")
        self.label_gewaehltes_leerrohr2 = QtWidgets.QLabel(self.tab)
        self.label_gewaehltes_leerrohr2.setGeometry(QtCore.QRect(360, 233, 231, 22))
        self.label_gewaehltes_leerrohr2.setStyleSheet("background-color: lightcoral;")
        self.label_gewaehltes_leerrohr2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_gewaehltes_leerrohr2.setObjectName("label_gewaehltes_leerrohr2")
        self.pushButton_automatisch = QtWidgets.QPushButton(self.tab)
        self.pushButton_automatisch.setGeometry(QtCore.QRect(0, 263, 141, 22))
        self.pushButton_automatisch.setObjectName("pushButton_automatisch")
        self.pushButton_Knoten = QtWidgets.QPushButton(self.tab)
        self.pushButton_Knoten.setGeometry(QtCore.QRect(0, 33, 191, 25))
        self.pushButton_Knoten.setObjectName("pushButton_Knoten")
        self.comboBox_AktivLR2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_AktivLR2.setGeometry(QtCore.QRect(360, 207, 231, 22))
        self.comboBox_AktivLR2.setObjectName("comboBox_AktivLR2")
        self.comboBox_AktivLR1 = QtWidgets.QComboBox(self.tab)
        self.comboBox_AktivLR1.setGeometry(QtCore.QRect(0, 207, 231, 22))
        self.comboBox_AktivLR1.setObjectName("comboBox_AktivLR1")
        self.comboBox_StatusGlobal = QtWidgets.QComboBox(self.tab)
        self.comboBox_StatusGlobal.setGeometry(QtCore.QRect(360, 263, 231, 22))
        self.comboBox_StatusGlobal.setObjectName("comboBox_StatusGlobal")
        self.pushButton_Auswahl = QtWidgets.QPushButton(self.tab)
        self.pushButton_Auswahl.setGeometry(QtCore.QRect(260, 102, 81, 71))
        self.pushButton_Auswahl.setObjectName("pushButton_Auswahl")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(410, 69, 121, 31))
        self.checkBox_2.setStyleSheet("#checkBox_1, #checkBox_2 { spacing: 6px; }\n"
"\n"
"/* Track */\n"
"#checkBox_1::indicator, #checkBox_2::indicator {\n"
"  width: 30px; height: 15px;\n"
"  border-radius: 6px;\n"
"  border: 1px solid #b0b0b0;\n"
"  background: #cfcfcf;\n"
"}\n"
"\n"
"#checkBox_1::indicator:checked, #checkBox_2::indicator:checked {\n"
"  background: #4caf50;\n"
"  border-color: #3a9a3e;\n"
"}\n"
"\n"
"/* Knopf-Bild aus Ressource */\n"
"#checkBox_1::indicator:unchecked, #checkBox_2::indicator:unchecked {\n"
"  image: url(:/toggles/toggle_knob_left.svg);\n"
"}\n"
"#checkBox_1::indicator:checked, #checkBox_2::indicator:checked {\n"
"  image: url(:/toggles/toggle_knob_right.svg);\n"
"}\n"
"")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_1.setGeometry(QtCore.QRect(100, 69, 121, 31))
        self.checkBox_1.setStyleSheet("#checkBox_1, #checkBox_2 { spacing: 6px; }\n"
"\n"
"/* Track */\n"
"#checkBox_1::indicator, #checkBox_2::indicator {\n"
"  width: 30px; height: 15px;\n"
"  border-radius: 6px;\n"
"  border: 1px solid #b0b0b0;\n"
"  background: #cfcfcf;\n"
"}\n"
"\n"
"#checkBox_1::indicator:checked, #checkBox_2::indicator:checked {\n"
"  background: #4caf50;\n"
"  border-color: #3a9a3e;\n"
"}\n"
"\n"
"/* Knopf-Bild aus Ressource */\n"
"#checkBox_1::indicator:unchecked, #checkBox_2::indicator:unchecked {\n"
"  image: url(:/toggles/toggle_knob_left.svg);\n"
"}\n"
"#checkBox_1::indicator:checked, #checkBox_2::indicator:checked {\n"
"  image: url(:/toggles/toggle_knob_right.svg);\n"
"}\n"
"")
        self.checkBox_1.setObjectName("checkBox_1")
        self.listWidget_Leerohr1_2 = QtWidgets.QListWidget(self.tab)
        self.listWidget_Leerohr1_2.setGeometry(QtCore.QRect(200, 0, 391, 61))
        self.listWidget_Leerohr1_2.setObjectName("listWidget_Leerohr1_2")
        self.pushButton_PDF = QtWidgets.QPushButton(self.tab)
        self.pushButton_PDF.setGeometry(QtCore.QRect(299, 263, 51, 22))
        self.pushButton_PDF.setObjectName("pushButton_PDF")
        self.tabWidget.addTab(self.tab, "")
        self.pushButton_Import = QtWidgets.QPushButton(KabelVerlegungsToolDialogBase)
        self.pushButton_Import.setEnabled(False)
        self.pushButton_Import.setGeometry(QtCore.QRect(305, 843, 84, 23))
        self.pushButton_Import.setObjectName("pushButton_Import")
        self.button_box = QtWidgets.QDialogButtonBox(KabelVerlegungsToolDialogBase)
        self.button_box.setGeometry(QtCore.QRect(3, 840, 581, 30))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Reset)
        self.button_box.setObjectName("button_box")
        self.pushButton_Datenpruefung = QtWidgets.QPushButton(KabelVerlegungsToolDialogBase)
        self.pushButton_Datenpruefung.setGeometry(QtCore.QRect(211, 843, 84, 23))
        self.pushButton_Datenpruefung.setObjectName("pushButton_Datenpruefung")
        self.button_box.raise_()
        self.pushButton_Datenpruefung.raise_()
        self.tabWidget.raise_()
        self.pushButton_Import.raise_()

        self.retranslateUi(KabelVerlegungsToolDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(KabelVerlegungsToolDialogBase)

    def retranslateUi(self, KabelVerlegungsToolDialogBase):
        _translate = QtCore.QCoreApplication.translate
        KabelVerlegungsToolDialogBase.setWindowTitle(_translate("KabelVerlegungsToolDialogBase", "Leerrohr Verbinden"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("KabelVerlegungsToolDialogBase", "Verbindung erstellen"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("KabelVerlegungsToolDialogBase", "Tabellarische Ansicht"))
        self.pushButton_verbindung.setText(_translate("KabelVerlegungsToolDialogBase", "Verbindung Wählen"))
        self.label_gewaehltes_leerrohr1.setText(_translate("KabelVerlegungsToolDialogBase", "Gewähltes Leerrohr 1"))
        self.pushButton_verbindung_loeschen.setText(_translate("KabelVerlegungsToolDialogBase", "Verbindungen löschen"))
        self.pushButton_leerrohr1.setText(_translate("KabelVerlegungsToolDialogBase", "Über Karte wählen"))
        self.pushButton_leerrohr2.setText(_translate("KabelVerlegungsToolDialogBase", "Über Karte wählen"))
        self.label_gewaehltes_leerrohr2.setText(_translate("KabelVerlegungsToolDialogBase", "Gewähltes Leerrohr 2"))
        self.pushButton_automatisch.setText(_translate("KabelVerlegungsToolDialogBase", "Automatisch verbinden"))
        self.pushButton_Knoten.setText(_translate("KabelVerlegungsToolDialogBase", "Knoten wählen"))
        self.pushButton_Auswahl.setText(_translate("KabelVerlegungsToolDialogBase", "Auswahl \n"
"Bestätigt"))
        self.checkBox_2.setText(_translate("KabelVerlegungsToolDialogBase", "CheckBox"))
        self.checkBox_1.setText(_translate("KabelVerlegungsToolDialogBase", "CheckBox"))
        self.pushButton_PDF.setText(_translate("KabelVerlegungsToolDialogBase", "PDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("KabelVerlegungsToolDialogBase", "Leerohr Verbinden"))
        self.pushButton_Import.setText(_translate("KabelVerlegungsToolDialogBase", "Import"))
        self.pushButton_Datenpruefung.setText(_translate("KabelVerlegungsToolDialogBase", "Daten Prüfen"))
from . import Button_checkbox_rc
